name: Migrate Release Candidate to Staging

on:
  workflow_dispatch: # Allows manual triggers as needed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENCRYPTION_PASSWORD: ${{ secrets.TIGER_GRADES_ENCRYPTION_PASSWORD }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Content Segmentation of Release Candidate Data
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            wp search-replace 'release.tigergrades.com' 'staging.tigergrades.com' --export=${{ secrets.TIGER_GRADES_PATH }}/staging/migration.sql --skip-columns=guid --skip-tables=wp_users --path=${{ secrets.TIGER_GRADES_PATH }}/release
      - name: Export Staging Backup
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            wp db export ${{ secrets.TIGER_GRADES_PATH }}/staging/backup.sql --path=${{ secrets.TIGER_GRADES_PATH }}/staging
          # --skip-triggers --skip-lock-tables --skip-add-drop-table --skip-add-locks --skip-create-options --skip-comments --skip-create-info --skip-drop-table --skip-extended-insert --skip-insert --skip-lock-tables --skip-quick --skip-replace --skip-set-charset --skip-triggers --skip-use-frm --skip-where --skip-add-drop-table --skip-add-locks --skip-create-options --skip-comments --skip-create-info --skip-drop-table --skip-extended-insert --skip-insert --skip-lock-tables --skip-quick --skip-replace --skip-set-charset --skip-triggers --skip-use-frm --skip-where
      - name: Compress Staging Backup
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            cd ${{ secrets.TIGER_GRADES_PATH }}/staging
            gzip -f backup.sql
      - name: Encrypt Staging Backup
        uses: ./.github/actions/encrypt
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          file: ${{ secrets.TIGER_GRADES_PATH }}/staging/backup.sql.gz
      - name: Import Release Migration to Staging
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            wp db import ${{ secrets.TIGER_GRADES_PATH }}/staging/migration.sql --path=${{ secrets.TIGER_GRADES_PATH }}/staging
      - name: Compress Release Migration
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            cd ${{ secrets.TIGER_GRADES_PATH }}/staging
            gzip -f migration.sql
      - name: Encrypt Release Migration
        uses: ./.github/actions/encrypt
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          file: ${{ secrets.TIGER_GRADES_PATH }}/staging/migration.sql.gz
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          known_hosts: ${{ secrets.HOSTINGER_KNOWN_HOSTS }}
          name: ${{ secrets.HOSTINGER_KEY_TYPE }}
          if_key_exists: replace # optional, defaults to fail
      - name: Check SSH key
        run: |
          ls -la ~/.ssh/
          ssh-add -l
      - name: Debug SSH key
        run: |
          ssh -v -p ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }} "pwd"
      - name: Transfer Staging Backup to GitHub Runner
        run: |
          scp -v -P ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.TIGER_GRADES_PATH }}/staging/backup.sql.gz.enc ./backup/staging/$(date +%Y-%m-%d-%H-%M-%S).sql.gz.enc
      - name: Transfer Release Migration to GitHub Runner
        run: |
          scp -P ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_USERNAME }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.TIGER_GRADES_PATH }}/staging/migration.sql.gz.enc ./migration/staging/$(date +%Y-%m-%d-%H-%M-%S).sql.gz.enc
      - name: Commit and Push to git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Release Candidate to Staging Workflow"
          git push



