name: Migrate Release Candidate to Staging

on:
  workflow_dispatch: # Allows manual triggers as needed

jobs:
  deploy-and-backup:
    runs-on: ubuntu-latest
    steps:
      # Setup steps
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          known_hosts: ${{ secrets.HOSTINGER_KNOWN_HOSTS }}
          name: ${{ secrets.HOSTINGER_KEY_TYPE }}

      # Backup steps
      - name: Export Staging Backup
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            wp db export ${{ secrets.TIGER_GRADES_PATH }}/staging/backup.sql \
            --path=${{ secrets.TIGER_GRADES_PATH }}/staging

      # Migration steps
      - name: Content Segmentation of Release Candidate Data
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            wp search-replace 'release.tigergrades.com' 'staging.tigergrades.com' \
            --export=${{ secrets.TIGER_GRADES_PATH }}/staging/migration.sql \
            --path=${{ secrets.TIGER_GRADES_PATH }}/release \
            --skip-columns=guid \
            --skip-tables=wp_users
      - name: Import Release Migration to Staging
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          script: |
            wp db import ${{ secrets.TIGER_GRADES_PATH }}/staging/migration.sql \
            --path=${{ secrets.TIGER_GRADES_PATH }}/staging

      # Artifact handling steps
      ## Backup
      - name: Compress Staging Backup
        uses: ./.github/actions/compress
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          path: ${{ secrets.TIGER_GRADES_PATH }}/staging
          file: backup.sql
      - name: Encrypt Staging Backup
        uses: ./.github/actions/encrypt
        env:
          ENCRYPTION_PASSWORD: ${{ secrets.TIGER_GRADES_ENCRYPTION_PASSWORD }}
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          file: ${{ secrets.TIGER_GRADES_PATH }}/staging/backup.sql.gz
      - name: Transfer Staging Backup to GitHub Runner
        uses: ./.github/actions/scp
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key_type: ${{ secrets.HOSTINGER_KEY_TYPE }}
          port: ${{ secrets.HOSTINGER_PORT }}
          path: ${{ secrets.TIGER_GRADES_PATH }}/staging
          file: backup.sql.gz.enc

      ## Migration
      - name: Compress Release Migration
        uses: ./.github/actions/compress
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          path: ${{ secrets.TIGER_GRADES_PATH }}/staging
          file: migration.sql
      - name: Encrypt Release Migration
        uses: ./.github/actions/encrypt
        env:
          ENCRYPTION_PASSWORD: ${{ secrets.TIGER_GRADES_ENCRYPTION_PASSWORD }}
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key: ${{ secrets.HOSTINGER_PRIVATE_KEY }}
          port: ${{ secrets.HOSTINGER_PORT }}
          file: ${{ secrets.TIGER_GRADES_PATH }}/staging/migration.sql.gz
      - name: Transfer Release Migration to GitHub Runner
        uses: ./.github/actions/scp
        with:
          host: ${{ secrets.HOSTINGER_HOST }}
          username: ${{ secrets.HOSTINGER_USERNAME }}
          key_type: ${{ secrets.HOSTINGER_KEY_TYPE }}
          port: ${{ secrets.HOSTINGER_PORT }}
          path: ${{ secrets.TIGER_GRADES_PATH }}/staging
          file: migration.sql.gz.enc

      ## Git
      - name: Configure Git and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Migrate Release Candidate to Staging Workflow"
          git push origin HEAD:${{ github.ref }}
